### PR TITLE
Gains the ability to have cookie name from manager

### PR DESCRIPTION
**Pull request by corebreaker**
Add a methods to access to:
- cookie name on cookie manager after it has been configured,
- manager store (getter in managers).

### CODE REVIEW

**Comment by icza** [comment]
Nice additions, but as it is, this code is not safe for concurrent use.

You modified `NewCookieManagerOptions()` to modify the passed options if it has "missing" values, and this creates a race if `NewCookieManager()` is called from multiple goroutines which uses the global variable `zeroCookieMngrOptions`. Also its name becomes "invalid" as it will be modified.

Also the name `DEFAULT_SESSION_ID_COOKIE_NAME` is not idiomatic in Go.

**Comment by icza** [comment]
Also, you might say I'm "picky" here, but modifying fields of the passed options and _later_ use it to initialize unexported fields of `CookieManager` is a vulnerability point.

Since the options is passed in as a pointer, theoretically it's possible for the caller to modify the pointed value (a field of the struct as the caller has the options) concurrently, in another goroutine, between the point where `NewCookieManagerOptions()` set default to a field **and** when this field is used in the end to initialize a field of the `CookieManager` struct.

**Comment by corebreaker** [comment]
Thank for make them notice me.

The aims is to have options real options used on a CookieManager instance. To make it thread-safe, we can add a GetOption() method on CookieManager.

The idea of DEFAULT_SESSION_ID_COOKIE_NAME constant is is to have default value of cookie name, i mean, the value to use when cookie name has not put in options. How would you do it ?

**Comment by icza** [comment]
There was already a default session ID cookie name in the original code:

	if m.sessIDCookieName == "" {
		m.sessIDCookieName = "sessid"
	}

What I meant was only that the identifier `DEFAULT_SESSION_ID_COOKIE_NAME` is not idiomatic in Go, in Go you shouldn't use all uppercase identifiers. See https://golang.org/doc/effective_go.html#mixed-caps

**Comment by icza** [comment]
I agree on the part that it should be possible to tell what options it ends up using. I think it's better to just add methods to `CookieManager` for this purpose.

I also didn't expose the `Store` as that is passed in when creating the manager, so the caller already has it. I tried to keep the `Manager` interface minimal.

So if you agree, I reject this PR and simply add methods to `CookieManager`.

**Comment by corebreaker** [comment]
Ok i agree

**Comment by icza** [comment]
FYI, added methods to `CookieManager`: https://github.com/icza/session/commit/18040e14e0486c9cc8c96cd4af691ef1f1fe7915

**Pull request closed without merging**
